name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            materials/problems.tex
            materials/complexity_theory.tex
            materials/decidability_and_computability.tex
            materials/languages_and_grammars.tex
            materials/regular_languages.tex
            materials/context_free_languages.tex
          handouts: |
            materials/problems.tex
            materials/complexity_theory.tex
            materials/decidability_and_computability.tex
            materials/languages_and_grammars.tex
            materials/regular_languages.tex
            materials/context_free_languages.tex
